install java 17

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -156,6 +156,25 @@ jobs:
           command: bundle exec fastlane push_pods
           no_output_timeout: 30m
 
+  install-sdkman:
+    description: Install SDKMAN
+    steps:
+      - run:
+          name: Installing SDKMAN
+          command: |
+            if curl -s "https://get.sdkman.io?rcupdate=false" | bash; then
+              echo -e '\nsource "/root/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
+              source $BASH_ENV
+            else
+              echo "Error installing SDKMAN, continuing with default Java" >&2
+            fi
+      - run:
+          name: Setup Java environment
+          command: |
+            if ! sdk env install; then
+              echo "Error installing Java SDK through SDKMAN, continuing with default Java" >&2
+            fi
+
   test-android:
     executor:
       name: android/android-machine
@@ -164,6 +183,7 @@ jobs:
     steps:
       - checkout:
           path: ~/purchases-hybrid-common
+      - install-sdkman
       - revenuecat/prepare-android
       - run:
           name: Run Tests
